openapi: 3.0.0
info:
  title: Fantasy Football Reporting App
  description: Takes API requests, creates and executes SQL, returns results
  version: 1.0.0

# Paths supported by the server application
paths:
  /get_managers:
    get:
      tags:
        - get_mangers
      description: Return all managers
      summary: Return all managers
      operationId: db_service.get_managers
      responses:
        200:
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "A Bag of Six"
                    owner:
                      type: string
                      example: Rob